# src/config.py

# Azure Speech Services Config
AZURE_SPEECH_KEY = "YOUR_AZURE_SPEECH_KEY"
AZURE_SPEECH_REGION = "YOUR_AZURE_REGION"

# Azure OpenAI (GPT-4) Config
OPENAI_API_KEY = "YOUR_OPENAI_KEY"
OPENAI_API_BASE = "https://YOUR_OPENAI_INSTANCE.openai.azure.com/"
OPENAI_API_VERSION = "2023-06-01-preview"

# Azure Communication Services (ACS) Config
ACS_CONNECTION_STRING = "YOUR_ACS_CONNECTION_STRING"

